#pragma once

// glTF 2.0 / GLB mesh loading (cgltf) and a minimal GLB writer. The loader pulls
// POSITION / NORMAL / TEXCOORD_0 + indices from every triangle primitive (applying
// node world transforms), producing engine StaticVertex data; tangents are
// generated by Engine::createMesh. The writer is used by --import-asset to convert
// the OBJ source assets to GLB.

#include "Engine/SceneFrame.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace pulse {

// Load a .glb/.gltf into engine vertices + indices. Returns false on any error
// (caller fails loud). tangent/color are defaulted; uv1 unused.
bool loadGltfMesh(const std::string& path,
                  std::vector<StaticVertex>& verts, std::vector<uint32_t>& indices);

// Write a single-primitive GLB (positions/normals/uv0 + 32-bit indices, identity
// node transform) from engine vertex data. Used by the offline --import-asset.
bool writeGlb(const std::string& path,
              const std::vector<StaticVertex>& verts, const std::vector<uint32_t>& indices);

// Minimal Wavefront OBJ reader (v / vn / vt / triangulated f), producing indexed
// engine vertices. Used by --import-asset to convert the OBJ source to GLB.
bool loadObjMesh(const std::string& path,
                 std::vector<StaticVertex>& verts, std::vector<uint32_t>& indices);

// One material group inside a kit tile (a contiguous run of geometry sharing a
// material, e.g. "brickwall1" / "stonefloor" / "stonetrims").
struct TileSubmesh {
    std::string               material;
    std::vector<StaticVertex> verts;
    std::vector<uint32_t>     indices;
    // PBR material data pulled from the glTF (for real-asset kits). Texture URIs are relative to
    // the glTF file's directory ("" = none). metallic/roughness are the scalar factors; the
    // baseColorFactor is also baked into vertex COLOR by the loader, so untextured kits still tint.
    Vec4f       baseColorFactor{ 1, 1, 1, 1 };
    float       metallic = 1.0f;
    float       roughness = 1.0f;
    Vec3f       emissiveFactor{ 0, 0, 0 };
    std::string baseColorTex;   // sRGB albedo
    std::string normalTex;      // tangent-space normal (linear)
    std::string ormTex;         // packed occlusion/roughness/metallic (glTF metallicRoughness; linear)
    std::string emissiveTex;    // sRGB emissive map
    // GLB-embedded images have no URI; copy the encoded PNG/JPG bytes while cgltf's buffers live.
    std::vector<uint8_t> baseColorImage;
    std::vector<uint8_t> normalImage;
    std::vector<uint8_t> ormImage;
    std::vector<uint8_t> emissiveImage;
};

// A single modular-kit tile, grouped by material and re-centered so the footprint
// centre sits at the origin in X/Z and the floor at Y=0. size* is the world-space
// bounding extent after re-centering (kit source units; the caller scales to grid).
struct KitTile {
    std::string               name;        // e.g. "Room.X", "Hall.L", "Stairs"
    std::vector<TileSubmesh>  submeshes;
    float sizeX = 0.0f, sizeY = 0.0f, sizeZ = 0.0f;
};

// Load every named tile from a modular-kit glTF that names its meshes
// "<tile>_<material>_<index>" (the Sketchfab/FBX convention). Node world transforms
// are applied; "collision" proxy meshes are skipped; each tile is re-centered.
// Returns false if no tiles were found.
bool loadGltfTiles(const std::string& path, std::vector<KitTile>& tiles);

// Load a WHOLE glTF as one object: all primitives (node world transforms applied) grouped by
// their glTF material name into submeshes, then re-centered ONCE as a unit (footprint centre to
// origin in X/Z, floor at Y=0). Unlike loadGltfTiles (which re-centers each named tile on its
// own), this keeps a multi-part prop (e.g. a tree's trunk + foliage) in its authored layout, so
// it can be instanced as a single prop. Returns false if the glTF has no geometry.
bool loadGltfWhole(const std::string& path, KitTile& out);

} // namespace pulse
